export const ICT_SUBJECTS = {
  grade11: {
    firstSem: {
      GEN_MATH: "",
      PD: "",
      PFPL: "",
      NET_TECH_1: "",
      KPWKP: "",
      JAVA_1: "",
      EAPP: "",
      OCC: "",
      CLED01: "",
      PEH1: "",
    },
    secondSem: {
      SP: "",
      CLED02: "",
      JAVA_NET_2: "",
      PEH_2: "",
      PR_1: "",
      PPIITP: "",
      RWS: "",
      CLPW: "",
      PR1: "",
      UCSP: "",
      NTECH2: "",
    },
  },
  grade12: {
    firstSem: {
      NET_TECH_3: "",
      PR2: "",
      CLE03: "",
      CPAR: "",
      PEH3: "",
      ELS: "",
      IPHP: "",
      MIL: "",
      JAVA_NET_3: "",
    },
    secondSem: {
      WI: "",
      ENTREP: "",
      PS: "",
      III: "",
      EM_TECH: "",
      JAVA_4: "",
      NTECH4: "",
      CLED04: "",
      PEH4: "",
    },
  },
};

export const STEM_SUBJECTS = {
  grade11: {
    firstSem: {
      GEN_MATH: "",
      E_TECH: "",
      ELS: "",
      KPWKP: "",
      PRE_CAL: "",
      IPHP: "",
      OCC: "",
      CLED01: "",
      PEH1: "",
    },
    secondSem: {
      SP: "",
      CLEDO02: "",
      BCAL: "",
      PR1: "",
      PPIITTP: "",
      RWS: "",
      DRRR: "",
      PD: "",
      GCHEM1: "",
    },
  },
  grade12: {
    firstSem: {
      CLP2: "",
      GPHY1: "",
      CLE03: "",
      CPAR: "",
      PEH3: "",
      CLPW: "",
      PFPL: "",
      EAPP: "",
      MIL: "",
      GBIO1: "",
      UCSP: "",
    },
    secondSem: {
      WI: "",
      ENTREP: "",
      PR2: "",
      III: "",
      GCHEM2: "",
      GBIO2: "",
      CLED04: "",
      PEH4: "",
      GPHY2: "",
    },
  },
};

export const HUMSS_SUBJECTS = {
  grade11: {
    firstSem: {
      GEN_MATH: "",
      E_TECH: "",
      CPAR: "",
      KPWKP: "",
      ELS: "",
      EAPP: "",
      OCC: "",
      CLED01: "",
      PEH1: "",
      UCSP: "",
    },
    secondSem: {
      SP: "",
      CLED02: "",
      DISS: "",
      PEH2: "",
      PFPL: "",
      PPIITTP: "",
      RWS: "",
      CLPW: "",
      PD: "",
      PPG: "",
    },
  },
  grade12: {
    firstSem: {
      PS: "",
      CW: "",
      DLASS: "",
      CLE03: "",
      PR1: "",
      PEH3: "",
      IWRBS: "",
      IPHP: "",
      MIL: "",
    },
    secondSem: {
      WI: "",
      ENTREP: "",
      III: "",
      PR2: "",
      TNCTCC: "",
      CN: "",
      CLED04: "",
      PEH4: "",
      CESC: "",
    },
  },
};
export const ABM_SUBJECTS = {
  grade11: {
    firstSem: {
      GEN_MATH: "",
      PD: "",
      PR1: "",
      KPWKP: "",
      ELS: "",
      EAPP: "",
      OCC: "",
      CLED01: "",
      PEH1: "",
      UCSP: "",
    },
    secondSem: {
      PS: "",
      SP: "",
      CLED02: "",
      PEH2: "",
      EM_TECH: "",
      PPIITTP: "",
      RWS: "",
      OM: "",
      BM: "",
      FABM_1: "",
    },
  },
  grade12: {
    firstSem: {
      CLPW: "",
      PR2: "",
      CLE03: "",
      CPAR: "",
      PEH3: "",
      BF: "",
      IPHP: "",
      MIL: "",
      FABM2: "",
    },
    secondSem: {
      WI: "",
      ENTREP: "",
      BM: "",
      III: "",
      PFPL: "",
      AE: "",
      BESR: "",
      CLED04: "",
      PEH4: "",
    },
  },
};
